name: ili2pg-scram
on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**.md'
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Version?'
    #     required: true

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica' 
          java-version: '8'
          
      - name: Build fat jar
        run: ./gradlew clean shadowJar

      - name: Release distributions
        run: |
          ./gradlew -i jreleaserRelease
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ success() && github.ref == 'refs/heads/main'}}
